version: '3.8'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: main
      DB_USERNAME: admin
      DB_PASSWORD: admin
    networks:
      - app
    command: >
      sh -c "php artisan migrate:fresh --seed && php artisan serve --host=0.0.0.0"
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'main'
      MYSQL_USER: 'admin'
      MYSQL_ROOT: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - app
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 3306:3306

networks:
  app:
    driver: bridge
